### ISSUE TITLE
Write a validation test tool to compare C# results against python server

### ISSUE THREAD

**Issue by jflavoie33** [RNCan/BioSIM_Web_API_Prod#16]
Execute requests on the python server, store the results, then launch the same requests on the C# server and compare the results.

**Comment by donenrique24** [comment]
We used the tests available in the Java client to do that. The C# server was started from VS while the Python server was running. The tests were performed on both servers. Five out of 41 tests failed with very small differences compared to expected values. The C# server was using the same DB than those of the Python server, so that the differences in the DB could be ruled out. 
After discussion with Rémi, it seems very most likely that these differences are due to the more recent implementation on the C# end. The Python server is running with a dll that is at least one year old.
